# XXX Testing shows that currently peer-relation-joined is run
# not just when the unit joins the peer relationship, but every
# time a new unit is added to the peer relationship. We want to
# update the config with the extra peers, but only restart the service
# if we're not already part of the cluster (ie. num nodes is 1).
- name: Update config with peer hosts
  tags:
    - peer-relation-joined
  template: src={{ charm_dir }}/templates/elasticsearch.yml
            dest=/etc/elasticsearch/elasticsearch.yml
            mode=0644
            backup=yes

# If multiple units are started simultaneously, peer-relation-joined
# may be called before the service is running.
- name: Wait until the local service is available
  tags:
    - peer-relation-joined
  wait_for: port=9200

- name: Record current cluster health
  tags:
    - peer-relation-joined
  uri: url=http://localhost:9200/_cluster/health return_content=yes
  register: cluster_health

- name: Restart if not part of cluster
  tags:
    - peer-relation-joined
  service: name=elasticsearch state=restarted
  when: cluster_health.json.number_of_nodes == 1

- name: Wait until the local service is available after restart
  tags:
    - peer-relation-joined
  wait_for: port=9200
  when: cluster_health.json.number_of_nodes == 1

- name: Pause to ensure that after restart unit has time to join.
  tags:
    - peer-relation-joined
  pause: seconds=30
  when: cluster_health.json.number_of_nodes == 1

- name: Record cluster health after restart
  tags:
    - peer-relation-joined
  uri: url=http://localhost:9200/_cluster/health return_content=yes
  register: cluster_health_after_restart
  when: cluster_health.json.number_of_nodes == 1

- name: Fail if unit is still not part of cluster
  tags:
    - peer-relation-joined
  fail: msg="Unit failed to join cluster during peer-relation-joined"
  when: cluster_health.json.number_of_nodes == 1 and cluster_health_after_restart.json.number_of_nodes == 1

